name: ci
on: pull_request
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Run unit tests
        run: go test ./...

  test:
    runs-on: ubuntu-latest
    env:
      BATON_INSTANCE_URL: http://localhost:8765
      BATON_USERNAME: test-admin
      BATON_PASSWORD: test-password
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build baton-pingfed
        run: go build ./cmd/baton-pingfed
      - name: Start test server
        run: go run ./cmd/test-server/ &
      - name: Wait for test server
        run: until curl -sf http://localhost:8765/pf-admin-api/v1/administrativeAccounts -o /dev/null; do sleep 0.5; done
      - name: Run baton-pingfed
        run: ./baton-pingfed
      - name: Install baton
        run: ./scripts/get-baton.sh && mv baton /usr/local/bin
      - name: Test grant/revoking admin entitlements
        env:
          BATON: baton
          BATON_PINGFEDERATE: ./baton-pingfed
          BATON_GRANT: "role:EXPRESSION_ADMINISTRATOR:assigned:user:admin"
          BATON_ENTITLEMENT: "role:EXPRESSION_ADMINISTRATOR:assigned"
          BATON_PRINCIPAL: "admin"
          BATON_PRINCIPAL_TYPE: "user"
        run: ./test/grant-revoke.sh
